### ISSUE TITLE
Move This Repo to an Organization

### ISSUE THREAD

**Issue by leafoflegend** [StarshipAcademy/StarshipAcademy#79]
This repo should be under an Org at this point, @EricTheRed-VT obviously, you're a great guy and I like you. But lets make a repo where everyone gets even credit and its not under your name! Id be surprised if your fellows/instructors haven't brought this up yet.

TLDR: GitHub has a feature to let you split the credit for this project amongst you guys - instead of it seeming like Erics project with some helpers. Do it.

**Comment by Jamad91** [comment]
Yeah, down with the Eric-ocracy!
